version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3080:3000" # Use 3080 on host, map to 3000 inside container
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
